import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f8fafc' },
  blob: { position: 'absolute', borderRadius: 999 },
  blobTopo: { width: 260, height: 260, top: -80, right: -60 },
  blobBase: { width: 320, height: 320, bottom: -120, left: -100 },
  scroll: {
    flexGrow: 1,
    paddingHorizontal: 22,
    paddingTop: Platform.OS === 'android' ? 40 : 16,
    paddingBottom: 32,
  },
  header: { alignItems: 'center', marginBottom: 22, marginTop: 12 },
  headerEmoji: { fontSize: 40, marginBottom: 6 },
  titulo: { fontSize: 24, fontWeight: '800', color: '#0f172a', textAlign: 'center' },
  subtitulo: { fontSize: 14, color: '#64748b', textAlign: 'center', marginTop: 6, lineHeight: 20, paddingHorizontal: 8 },
  card: {
    backgroundColor: '#ffffff', borderRadius: 20, padding: 20,
    shadowColor: '#0f172a', shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08, shadowRadius: 16, elevation: 4,
  },
  cardLabel: {
    fontSize: 13, fontWeight: '700', color: '#334155',
    marginBottom: 12, textTransform: 'uppercase', letterSpacing: 0.5,
  },
  linhaInputs: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'center' },
  grupoInput: { alignItems: 'center' },
  input: {
    width: 62, height: 56, borderRadius: 14, backgroundColor: '#f1f5f9',
    borderWidth: 1.5, borderColor: '#e2e8f0', textAlign: 'center',
    fontSize: 20, fontWeight: '700', color: '#0f172a',
  },
  inputAno: { width: 88 },
  legendaInput: { fontSize: 11, color: '#94a3b8', marginTop: 6, fontWeight: '600' },
  separador: { fontSize: 22, color: '#cbd5e1', marginHorizontal: 8, marginTop: 14, fontWeight: '700' },
  textoErro: { color: '#ef4444', fontSize: 13, marginTop: 14, textAlign: 'center', fontWeight: '600' },
  linhaBotoes: { flexDirection: 'row', marginTop: 20, gap: 12 },
  botaoLimpar: { paddingVertical: 14, paddingHorizontal: 18, borderRadius: 14, backgroundColor: '#f1f5f9' },
  textoBotaoLimpar: { color: '#475569', fontWeight: '700', fontSize: 15 },
  botaoCalcular: {
    flex: 1, paddingVertical: 14, borderRadius: 14, alignItems: 'center',
    shadowColor: '#0f172a', shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15, shadowRadius: 8, elevation: 3,
  },
  textoBotaoCalcular: { color: '#ffffff', fontWeight: '700', fontSize: 15 },
  resultadoCard: {
    backgroundColor: '#ffffff', borderRadius: 20, padding: 22, marginTop: 20,
    alignItems: 'center', borderWidth: 2, shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.1, shadowRadius: 16, elevation: 4,
  },
  badge: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 8, borderRadius: 999, gap: 8 },
  badgeEmoji: { fontSize: 20 },
  badgeTexto: { fontSize: 16, fontWeight: '800' },
  faixaDescricao: { fontSize: 12, color: '#94a3b8', marginTop: 8, fontWeight: '600' },
  linhaValores: { flexDirection: 'row', marginTop: 20, width: '100%', justifyContent: 'space-around' },
  valorBox: { alignItems: 'center' },
  valorNumero: { fontSize: 32, fontWeight: '800' },
  valorLegenda: { fontSize: 12, color: '#64748b', marginTop: 2, fontWeight: '600' },
  rodape: { fontSize: 12, color: '#94a3b8', textAlign: 'center', marginTop: 26, lineHeight: 18, paddingHorizontal: 12 },
});